### ISSUE TITLE
Istio Ingress not behave properly when scaled

### ISSUE THREAD

**Issue by IbraAoad** [canonical/istio-ingress-k8s-operator#16]
### Bug Description

When Istio Ingress is scaled beyond 1, It goes in to error state. It should instead continue to work and it should scale custom deployments accordingly.

### To Reproduce

juju scale-application istio-ingress-k8s 2

### Environment

latest/edge

### Relevant log output

```shell
unit-istio-ingress-k8s-1: 23:13:37 ERROR unit.istio-ingress-k8s/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-istio-ingress-k8s-1/charm/./src/charm.py", line 374, in <module>
    main(IstioIngressCharm)
  File "/var/lib/juju/agents/unit-istio-ingress-k8s-1/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-istio-ingress-k8s-1/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-istio-ingress-k8s-1/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-istio-ingress-k8s-1/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-istio-ingress-k8s-1/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-istio-ingress-k8s-1/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-istio-ingress-k8s-1/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-istio-ingress-k8s-1/charm/./src/charm.py", line 135, in _on_config_changed
    self._sync_all_resources()
  File "/var/lib/juju/agents/unit-istio-ingress-k8s-1/charm/./src/charm.py", line 291, in _sync_all_resources
    self._sync_ingress_resources()
  File "/var/lib/juju/agents/unit-istio-ingress-k8s-1/charm/./src/charm.py", line 308, in _sync_ingress_resources
    raise RuntimeError("Ingress can only be provided on the leader unit.")
RuntimeError: Ingress can only be provided on the leader unit.
```

**Comment by ca-scribner** [comment]
Notes from backlog refinement

Approaches for handling charm scale:
1. the Charm is always idempotent and looks at the entire state then reconciles all objects
2. all action in the charm is behind a leader guard.  Only the leader does state reconciliation

Other things to consider when doing this:
1. How is removal handled for scaled units?  If we scale from 2-->1, who receives what events?  We need to ensure that the departing unit doesn't delete everything, but also that the Gateway object's replicas scale from 2->1
  * can we stop `.delete()`ing the resources in our remove event handling and instead just let Juju clean up automatically when the application is removed?  Juju should annotate the objects so this works
2. we have pebble containers for metrics proxy on each unit.  Is it appropriate for them to be scraped, or should metrics proxy only be on the leader?

Tentative decisions:
* for handling scale, try implementing scaling without the leader guard and see if there's any negative consequences.  Maybe comment somewhere that the charm cannot use unit name (which would differ by unit)?

**Comment by dstathis** [comment]
For number 2, this needs to be determined for all custom resource k8s charms so it is outside of the scope of this issue. For now it is  okay that each unit will scrape all pods.

**Comment by ca-scribner** [comment]
Decisions from backlog refinement: 
* In the near-term, we will keep creating a Gateway object and letting Istio "implement" the gateway from that object.  To control scaling, we will use a HorizontalPodAutoscaler as suggested [in the istio docs](https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/#automated-deployment)
* For the longer term, we will do a spike to look at whether we should manually deploy and scale these, ideally using a sidecar for every gateway instance.

**Comment by ca-scribner** [comment]
As discussed [here](https://github.com/canonical/istio-ingress-k8s-operator/pull/61#discussion_r2056539971), we chose to handle the `remove` event by doing:

```python
def _on_remove(self, _):
  if self.model.app.planned_units() > 0:
    return
  
  # remove things
```

This is because:
* Juju does not depose a leader before removing that unit, so the removal of a leader unit does not equate to the removal of the application
* Juju does not guarantee that, on removal, a leader must exist.  Thus, application may occur without any leader being removed
